### ISSUE TITLE
Error after transcribe service called

### ISSUE THREAD

**Issue by coder1211** [aws-samples/amazon-connect-realtime-transcription#13]
Hi, I believe I have followed all the steps but when I run the example using a call into Amazon connect I get an error after the Transcribe Service is called: 

2019-05-03 19:43:08 INFO KVSTranscribeStreamingLambda:155 - Calling Transcribe service..
2019-05-03 19:43:10 DEBUG TranscribeStreamingRetryClient:163 - Error occured: software.amazon.awssdk.core.exception.SdkClientException

Any idea what would be causing that or where I should be looking for more logs? Sorry very new to this any help appreciated.

**Comment by coder1211** [comment]
I have managed to get your example code working in the Virgina region, but the same code and setup generates the error above if I try to use the Frankfurt region?

**Comment by efh365** [comment]
Hi coder1211. Can you add more of the stack trace from that exception?

**Comment by coder1211** [comment]
Hi, thanks for the interest, how would I add more stack trace? Can I get further stack trace from cloudwatch or would I go to the console? So I kept trying to get it to work using different regions and different bar files and I have got it to work after recompiling the code with a new jar file version: transcribestreaming-2.5.42.jar.

**Comment by efh365** [comment]
The stack trace can be found in cloudwatch logs under /aws/lambda/<TranscribeFunctionName>

So does updating to the new jar solve your problem?

**Comment by coder1211** [comment]
Yes changing the bar file to the newest release has made it work with the transcribe region of Ireland.

**Comment by coder1211** [comment]
I will close this issue given I have got what I needed.
