### ISSUE TITLE
Amazon Connect with CFlow and Lex Bot is not included in the Recordings on S3 Bucket

### ISSUE THREAD

**Issue by cjbersabal07** [aws-samples/amazon-connect-realtime-transcription#14]
Hi Dev Team,

I tried your code in this repository. And it's working fine, my problem is the user interaction  with the Lex Bot is not included in the call recording. 

Thanks.

**Comment by efh365** [comment]
Hi cjbersabal07. Thanks for your question. The default configuration starts the KVS streaming once the agent answers the phone call. This is denoted by using "NOW" in the KvsTranscriber lambda function for the "START_SELECTOR_TYPE" environment variable. If you instead would like to start the streaming at the point in the Contact Flow that the Start KVS Streaming block is called, update the environment variable to instead be "FRAGMENT_NUMBER". 

Please let me know if that fixes your problem.

**Comment by cjbersabal07** [comment]
![image](https://user-images.githubusercontent.com/24492553/59079322-c68da180-8915-11e9-9bc9-d8593c063d70.png)

Hi efh365, 

Thanks for the response. But after setting the "START_SELECTOR_TYPE" to "FRAGMENT_NUMBER" as you mentioned above. I still find no luck to record include AWS LEX Bot on the S3 Recording.

**Comment by efh365** [comment]
Oh sorry, let me clarify. You should be able to hear the customer while in queue, not the Lex Bot. Currently we only support streaming audio from the customer. Streaming the audio that the customer hears is not currently supported.

**Comment by cjbersabal07** [comment]
Hi efh365,

Ow. but does it have a similar approach with this one? https://docs.aws.amazon.com/connect/latest/adminguide/customer-voice-streams.html

Btw. thank you for your response.

**Comment by efh365** [comment]
Yes, that documentation describes how the Start Media Streaming block is used in the Contact Flow. So you should be able to hear the customer audio while they are talking to Lex, but you cannot hear what Lex is saying to the customer.

**Comment by cjbersabal07** [comment]
Okay I see. It would be great if Lex is included in the audio. Thanks for your answer. It is a case closed for me. 

Cheers.
