### ISSUE TITLE
Question: what does the web_socket_connections do

### ISSUE THREAD

**Issue by czhao028** [aws-samples/amazon-connect-realtime-transcription#15]
Just a quick question, what is there for? I looked at the AWS DynamoDB table and it was completely empty. In the template, it's not related to anything else. I'm a bit new to web development so I apologize if this is a simple question. Thanks

**Comment by efh365** [comment]
The web_socket_connections table keeps track of the open connections. If you look at the onConnect and onDisconnect lambda functions you will see that they add and remove the web sockets from the table as the call is accepted and terminated, respectively. So the table should be empty if you are looking at it while there is no call in progress.

**Comment by czhao028** [comment]
Ok thanks!
