### ISSUE TITLE
Upload code for Lambda functions

### ISSUE THREAD

**Issue by czhao028** [aws-samples/amazon-connect-realtime-transcription#16]
I'm trying to figure out how the kvsConsumerTrigger lambda function works (the one that triggers kvsTranscriber, or the pre-packaged lambda function in the README). However, I'm not seeing the code anywhere & access to the s3 object is denied: would the owners be able to upload that code for learning purposes?

**Comment by efh365** [comment]
Which S3 object are you trying to access? The README has an example of the trigger lambda function near the bottom of the page. Have you tried using that?

**Comment by czhao028** [comment]
Yes that example lambda function is for kvstranscribe, which is called by
kvsConsumerTrigger (which I'm looking for).

**Comment by efh365** [comment]
The KVS Transcribe lambda function is the zip of all the java code in this repo. The KVS Trigger lambda function is the example one in the README.

**Comment by czhao028** [comment]
Really? How do you know this?

**Comment by czhao028** [comment]
The trigger function in the readme is the most basic trigger function
possible, not the one that's used by
https://aws.amazon.com/solutions/ai-powered-speech-analytics-for-amazon-connect/

**Comment by efh365** [comment]
If you are following that solution, you can find the trigger function here: https://github.com/awslabs/ai-powered-speech-analytics-for-amazon-connect/tree/master/source/kvs_trigger

You can also download the contents from the Lambda function that was created by that CloudFormation template and view it that way.

**Comment by czhao028** [comment]
Thanks so much!
