### ISSUE TITLE
Can I request a much clearer step by step instruction

### ISSUE THREAD

**Issue by ember32** [aws-samples/amazon-connect-realtime-transcription#18]
Hi, I'm an aspiring AWS learner and a beginner in this craft. May I ask for a more detailed and noob-friendly step by step instructions? 

Thanks a lot!

**Comment by ember32** [comment]
Hi, I manage to work it around and now I can call my number (Amazon Connect) and record my input, save it to S3 and DynamoDB. 

May I ask what will I do regarding the Amazon Kinesis Video Stream part? Because at the start , I haven't touched that SERVICE. I do not know what its function to this activity. 

Thanks!

**Comment by efh365** [comment]
Great to hear that you got it to work! What specifically would you like to know about KVS? In the contact flow there is a block called "Start Streaming" in which a KVS stream starts streaming audio from the customer. The KVS Transcriber Lambda function then processes that audio and sends it to Transcribe then uploads the closed stream to S3. When the call ends or when the block "Stop Streaming" is hit, the stream is closed.

**Comment by ember32** [comment]
Thank you. :)
