### ISSUE TITLE
Need Clarificaton

### ISSUE THREAD

**Issue by robertmadsen** [aws-samples/amazon-connect-realtime-transcription#2]
Is the amazon-connect-realtime-transcription.zip example ready to upload to Lamba or is a Gradle build required first? Thx.

**Comment by groverkaran11** [comment]
It's ready to be uploaded as a Lambda. But you would need to configure the environment variables

**Comment by robertmadsen** [comment]
Thanks for that clarification.

Also:

  1.  if I do want to build the amazon-connect-realtime-transcription-master, then I do need to use Gradle, correct?
  2.  And I have to download and integrate amazon-kinesis-video-streams-parser-library-master?




________________________________
