### ISSUE TITLE
Error when testing pre-packaged Lambda function

### ISSUE THREAD

**Issue by robertmadsen** [aws-samples/amazon-connect-realtime-transcription#3]
I have upload the pre-packaged Lambda zip into a Lambda function and filled in the properties. When I try to process

my flow, I get the following error:

08:56:50
START RequestId: 56764c7e-50af-4de9-941b-af2ffd087842 Version: $LATEST 

08:56:50
Class not found: om.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda: java.lang.ClassNotFoundException java.lang.ClassNotFoundException: om.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at ja
Class not found: om.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: om.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)


08:56:50
END RequestId: 56764c7e-50af-4de9-941b-af2ffd087842

**Comment by yaelhagg** [comment]
Looks like maybe you have a typo in the handler field, it looks like you are missing the "c" in com....... It should be: com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda::handleRequest

**Comment by robertmadsen** [comment]
Thank so much for your replay. I have been able to get the example to work.
