### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by robertmadsen** [aws-samples/amazon-connect-realtime-transcription#4]
**I am confused by the INPUT_KEY_PREFIX.**

1. Where does this valued come from?
2. What does this mean? **This file is expected to be present in RECORDINGS_BUCKET_NAME**

**An example would be helpful**
Could you provide an example of the complete table filled out with a description of where each piece of data comes from?

Here's my current attempt

APP_REGION: us-west-2
CONSOLE_LOG_TRANSCRIPT_FLAG: TRUE
INPUT_KEY_PREFIX: AspenCalls **<--I have no idea what this is supposed to be!**
RECORDINGS_BUCKET_NAME: arn:aws:s3:::aspen-call-bucket
RECORDINGS_KEY_PREFIX: CallRecordings <**-- Do I just make this up?**
RECORDINGS_PUBLIC_READ_ACL: TRUE
SAVE_PARTIAL_TRANSCRIPTS: TRUE
TABLE_CALLER_TRANSCRIPT: arn:aws:dynamodb:us-west-2:639689516630:table/AspenCalls
TRANSCRIBE_REGION: us-west-2

**Comment by yaelhagg** [comment]
INPUT_KEY_PREFIX is used to tell this lambda function the S3 prefix for the designated bucket that would be used to process audio files. It is not required unless you plan on processing audio files vs KVS Streams. 

RECORDINGS_KEY_PREFIX is where you want the lambda function to upload the WAV files after it is done consuming the stream.

RECORDINGS_BUCKET_NAME - this is **just** the bucket name, not the arn, so in your case it would just be: aspen-call-bucket

TABLE_CALLER_TRANSCRIPT: is **just** the dynamoDB table name, not the arn, so in your case it would be: AspenCalls

**Comment by robertmadsen** [comment]
Thanks so much or your help.
