### ISSUE TITLE
Trigger Function Deployment

### ISSUE THREAD

**Issue by robertmadsen** [aws-samples/amazon-connect-realtime-transcription#5]
How do the Trigger function invoke the real time transcription Java Lambda connect? I don't grok where that is happening.

The trigger lambda has a line of code

'FunctionName': process.env.transcriptionFunction

What is process.env.transcriptionFunction and how is it set?

**Comment by yaelhagg** [comment]
This is primarily meant for use with Amazon Connect, where you would need a Lambda function to "trigger" this transciption lambda function.  The code: 'FunctionName': process.env.transcriptionFunction is meant to define the name of "this" Java lambda function to be "triggered" and would be set as an Environment variable called: transcriptionFunction

What is your use case?

**Comment by robertmadsen** [comment]
Thanks. I figured out the linkeage:

1. Upload amazon-connect-realtime-transcription.zip as a Java Lambda function.  Copy the Lambda arn.
2. Create a node.js Lambda function and paste the trigger Lambda function code as the code body. Use the copied arn as the streamARN parameter. Copy this Lambda's arn.

3. Create an Invoke Lambda function node after the Start Media Streaming Node Paste the arn of the trigger Lambda function into Select a function


The two Lambda functions are now correctly linked together,

**Comment by yaelhagg** [comment]
One slight clarification for your Step 2: 
Create a node.js Lambda and paste the trigger function code as the code body. Copy the Java Lambda function "name" and put that as the value for the env variable "transcriptionFunction" (if you are using the node js code as is) for the Node JS function. Copy the node js arn which will be used in the Amazon Connect Contact Flow. **Tip**: Amazon Connect now has an improved way to select Lambda functions in the contact flow: https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-connect-simplifies-adding-aws-lambda-functions-to-contact-flows/
