### ISSUE TITLE
Code Clarification

### ISSUE THREAD

**Issue by robertmadsen** [aws-samples/amazon-connect-realtime-transcription#6]
Please clarify how the pieces of code provided in this example are related and used. There appear to be three:
1. amazon-connect-realtime-transcription-master (the GitHub repository
2. amazon-connect-realtime-transcription.zip (the pre-packaged Lambda function)
3 trigger Lamba function - the sample script you provided at the bottom of the example

Thanks

**Comment by yaelhagg** [comment]
Please provide your use case so I can better answer your question with context.

**Comment by robertmadsen** [comment]
Thanks. I figured out the linkeage:

1. Upload amazon-connect-realtime-transcription.zip as a Java Lambda function.  Copy the Lambda arn.
2. Create a node.js Lambda function and paste the trigger Lambda function code as the code body. Use the copied arn as the streamARN parameter. Copy this Lambda's arn.

3. Create an Invoke Lambda function node after the Start Media Streaming Node Paste the arn of the trigger Lambda function into Select a function


The two Lambda functions are now correctly linked together,
