### ISSUE TITLE
saveCallRecording variable not mentioned in documentation

### ISSUE THREAD

**Issue by ccalderon911217** [aws-samples/amazon-connect-realtime-transcription#9]
In order to save the audio file to an S3 bucket a variable called `saveCallRecording` needs to be set to true when the Java function is triggered. Such variable is not mentioned in the documentation or the sample lambda trigger function.

In my case, I chose to set it as a contact attribute in Connect and I send it in the payload from the trigger function:

```
let payload = {
		        streamARN: event.Details.ContactData.MediaStreams.Customer.Audio.StreamARN,
		        startFragmentNum: event.Details.ContactData.MediaStreams.Customer.Audio.StartFragmentNumber,
		        connectContactId: event.Details.ContactData.ContactId,
		        transcriptionEnabled: event.Details.ContactData.Attributes.transcribeCall === "true" ? true : false,
		        saveCallRecording: event.Details.ContactData.Attributes.saveCallRecording === "true" ? true : false
    		};
```

Thank you for the code though, it's great!

**Comment by yaelhagg** [comment]
Thanks for the feedback, we just recently added that flag. The documentation has now been updated.
